name: spectr-v1
channels:
  - conda-forge
dependencies:
  # python essentials
  - python=3.8
  - pip
  # important libraries
  - black
  - flake8
  - numpy
  - opencv=4.5.3
  - pytorch=1.10.0