name: spectr-v1
channels:
  - pytorch
  - conda-forge
dependencies:
  # python essentials
  - python=3.8
  - pip
  # important libraries
  - black
  - flake8
  - numpy
  - pytorch
  - pytorch-lightning
  - torchvision
